source 'https://rubygems.org'


gem 'rails', '4.2.1'

gem 'rails-api'

gem 'spring', :group => :development


gem 'sqlite3'

# We need to serialize the JSON a certain way so Ember can consume it
gem 'active_model_serializers', '~> 0.8.3'

# Security policy to allow Rails to use Ember on another port
gem 'rack-cors', :require => 'rack/cors'

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
